### ISSUE TITLE
Download the Cafe dataset in the linux system

### ISSUE THREAD

**Issue by JihuaPeng** [dk-kim/CAFE_codebase#4]
When i execute the command "sh scripts/download_datasets.sh", it prompts ”unzip: cannot find zipfile directory in one of Dataset.zip“. it seems that the download link in the download_datasets.sh is not valid. How can I download the dataset to my linux system？Thanks!

**Comment by dk-kim** [comment]
I update the path in the download_dataset.sh file as it was the old one.
