### ISSUE TITLE
train.py: error: argument --groundtruth: can't open './evaluation/gt_tracks_24.txt': [Errno 2] No such file or directory: './evaluation/gt_tracks_24.txt'

### ISSUE THREAD

**Issue by JihuaPeng** [dk-kim/CAFE_codebase#6]
When i execute this command ”sh scripts/train_cafe_view.sh“, it seems that there is no ./evaluation/gt_tracks_24.txt. Is this file missing? Thanks！

**Comment by dk-kim** [comment]
You can find gt_tracks_24.txt file in the dataset zip file, then follow the file structure in readme file. 
Please close issues if the response has resolved the problem.

**Comment by JihuaPeng** [comment]
After i have unzipped the dataset zip file, there is only gt_tracks.txt in the flie "evaluation". Are gt_tracks.txt and gt_tracks_24.txt the same file?

**Comment by dk-kim** [comment]
Yes, sorry for the confusion. I change the default file path in the train.py just before.
